<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-05-20 at 06:56:34.
 */
class usuarioTest extends PHPUnit_Framework_TestCase {

    /**
     * @var usuario
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new usuario;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert (13) == true.
     *
     * @covers usuario::getPerfil
     */
//    public function testGetPerfil() {
//        $this->assertEquals(
//                true
//                ,
//                $this->object->getPerfil(13)
//        );
//    }

    /**
     * Generated from @assert ('123', '$2y$10$WKsaSfshrvh463S2.qwxSeovfNCM/6PKtSNBeP3COsmb.13IkRZpe') == true.
     *
     * @covers usuario::verificarContrasena
     */
    public function testVerificarContrasena() {
        $this->assertEquals(
                true
                ,
                $this->object->verificarContrasena('123', '$2y$10$WKsaSfshrvh463S2.qwxSeovfNCM/6PKtSNBeP3COsmb.13IkRZpe')
        );
    }

    /**
     * Generated from @assert ('alfa') == true.
     *
     * @covers usuario::verificarUsuario
     */
    public function testVerificarUsuario() {
        $this->assertEquals(
                true
                ,
                $this->object->verificarUsuario('alfa')
        );
    }

    /**
     * @covers usuario::getUsuario
     * @todo   Implement testGetUsuario().
     */
//    public function testGetUsuario() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers usuario::getCorreo
//     * @todo   Implement testGetCorreo().
//     */
//    public function testGetCorreo() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers usuario::register
//     * @todo   Implement testRegister().
//     */
//    public function testRegister() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers usuario::insertarPerfil
//     * @todo   Implement testInsertarPerfil().
//     */
//    public function testInsertarPerfil() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

}
